name: Upstream Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  PR_BRANCH_NAME: upstream-sync
  PR_DEST_NAME: main

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    name: Sync with upstream
    
    steps:
    - name: Checkout upstream
      uses: actions/checkout@v3
      with:
        ref: mininet-master
    - name: Sync upstream
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        upstream_sync_repo: mininet/mininet
        upstream_sync_branch: master
        target_sync_branch: mininet-master
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new branch for PR
      if: steps.sync.outputs.has_new_commits == 'true'
      run: |
        git checkout -b upstream-sync
        git push -u origin ${{ env.PR_BRANCH_NAME }}
