name: Upstream Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    name: Sync with upstream
    
    steps:
    - name: Checkout upstream
      uses: actions/checkout@v3.0.0
      with:
        ref: mininet-master
    - name: Sync upstream
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        upstream_sync_repo: mininet/mininet
        upstream_sync_branch: master
        target_sync_branch: mininet-master
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create PR if there is new commit
      if: steps.sync.outputs.has_new_commits == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        base: main
        branch: upstream-sync
        delete-branch: true
